debug: true
logging:
  config: classpath:log4j2.yml
  level:
    org:
      springframwork:
        web: warn
spring:
  datasource:
    # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-practice
    username: root
    password: root
    # 数据库连接池
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 10
      max-wait-millis: 60000
      validation-query: select 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
  # jpa配置
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  # redis配置
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
  servlet:
    multipart:
      max-file-size: 50000000
      max-request-size: 100000000
server:
  port: 8888
